version: '2'

services:
  jsonbin:
    image: dylanburati/jsonbin2
    restart: always
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      JWT_SECRET:
      GSHEETS_LAMBDA_API_KEY:
      GSHEETS_LAMBDA_ENDPOINT:
      GSHEETS_FILE_ID:
    mem_limit: 512M
    ports:
      - "7000:7000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: jsonbin
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    mem_limit: 256M
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
