version: '3'

services:
  haproxy:
    build: ./docker/haproxy
    environment:
      DOMAINS: datagame.live www.datagame.live blog.datagame.live
      FULLCHAIN: /certs/fullchain.pem
    ulimits:
      nofile: 33000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - cert_data:/certs
      - acme_sh_data:/acme.sh
    depends_on:
      - jsonbin
    links:
      - jsonbin

  jsonbin:
    build: .
    restart: always
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      JWT_SECRET:
      GSHEETS_LAMBDA_API_KEY:
      GSHEETS_LAMBDA_ENDPOINT:
      GSHEETS_FILE_ID:
    ports:
      - "7000:7000"
    depends_on:
      - postgresql
    links:
      - postgresql

  postgresql:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: jsonbin
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
  cert_data: {}
  acme_sh_data: {}
