version: '3'

services:
  haproxy:
    build: ./docker/haproxy
    environment:
      UPSTREAM: jsonbin:7000
      DOMAINS: datagame.live www.datagame.live blog.datagame.live
      FULLCHAIN: /certs/fullchain.pem
    deploy:
      resources:
        limits:
          memory: 128M
    ulimits:
      nofile: 33000
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/local-certs:/certs
    depends_on:
      - jsonbin

  jsonbin:
    build: .
    restart: always
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      JWT_SECRET:
      GSHEETS_LAMBDA_API_KEY:
      GSHEETS_LAMBDA_ENDPOINT:
      GSHEETS_FILE_ID:
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "7000:7000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_DB: jsonbin
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
