on:
  push:
    branches:
      - master

name: Push to DigitalOcean Droplet

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x

      - name: Login to Docker Hub
        run: docker login -u dylanburati -p "${{ secrets.DOCKER_ACCESS_TOKEN }}"

      - name: Build, tag, and push image 'jsonbin2' to Docker Hub
        env:
          REGISTRY: docker.io
          REPOSITORY: dylanburati/jsonbin2
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ./gradlew build
          docker build -t $REGISTRY/$REPOSITORY:latest -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Get droplet address
        id: droplet
        run: |
          doctl compute droplet list --output json | \
              jq -r '.[] | select(.name == "music-search-instance-2") | .networks.v4[0].ip_address' | \
              { read IP; echo "::set-output name=ipv4::$IP"; }

      - name: SSH script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.droplet.outputs.ipv4 }}
          username: dylan
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: /etc/jsonbin2/upgrade.sh
